// Domain types shared across the engine, store, and UI.

export type Pattern =
  | 'horizontal_press'
  | 'horizontal_pull'
  | 'vertical_press'
  | 'vertical_pull'
  | 'squat'
  | 'hinge'
  | 'side_delts'
  | 'rear_delts'
  | 'biceps'
  | 'triceps'
  | 'calves'
  | 'abs'
  | 'traps'
  | 'forearms';

export const MAIN_PATTERNS: Pattern[] = [
  'horizontal_press',
  'horizontal_pull',
  'vertical_press',
  'vertical_pull',
  'squat',
  'hinge',
];

export const ISOLATION_PATTERNS: Pattern[] = [
  'side_delts',
  'rear_delts',
  'biceps',
  'triceps',
  'calves',
  'abs',
  'traps',
  'forearms',
];

export type LifeStatus = 'alive' | 'slowing' | 'ended';
export type Units = 'kg' | 'lb';
export type Language = 'en' | 'ar';

// ---------------------------------------------------------------------------
// Seed (generated by scripts/buildSeed.mjs from the xlsx)
// ---------------------------------------------------------------------------

export interface SeedExercise {
  order: number;
  nameEn: string;
  muscleAr: string;
  muscleKey: string;
  category: string;
  pattern: Pattern;
  isIsolation: boolean;
  videoUrl: string | null;
  repRange: [number, number];
  restSeconds: [number, number];
  setsByWeek: number[];
  deloadSets: number;
  weakPoints: string[];
}

export interface SeedDay {
  index: number;
  nameEn: string;
  nameAr: string;
  isRest: boolean;
  exercises: SeedExercise[];
}

export interface SeedProgram {
  name: string;
  author: string;
  weeks: number;
  hasDeload: boolean;
  days: SeedDay[];
}

export interface SeedVariation {
  nameEn: string;
  videoUrl: string | null;
  pattern?: Pattern; // per-exercise pattern (refined from the group's category)
  weakPoints: string[];
}

export interface SeedVariationGroup {
  category: string;
  categoryKey: string;
  muscleKey: string;
  pattern: Pattern;
  isIsolation: boolean;
  exercises: SeedVariation[];
}

export interface Seed {
  meta: { generatedAt: string; source: string; author: string; note: string };
  program: SeedProgram;
  variationLibrary: SeedVariationGroup[];
}

// ---------------------------------------------------------------------------
// Logged / user data
// ---------------------------------------------------------------------------

export interface SetEntry {
  weight: number;
  reps: number;
  isWarmup: boolean;
  rir?: number;
  restTaken?: number;
  done?: boolean;
}

/** One session's worth of logged data for a single exercise. */
export interface LoggedExercise {
  order: number; // program slot order within the day
  exerciseName: string; // English name = stable key
  pattern: Pattern;
  muscleKey: string;
  sets: SetEntry[];
  /** 0/1 progression rating (auto-computed, user may override). */
  rating?: 0 | 1;
  ratingOverridden?: boolean;
  note?: string;
}

export interface WorkoutSession {
  id: string;
  date: string; // ISO
  dayIndex: number;
  weekIndex: number; // 1-based
  status: 'in_progress' | 'completed';
  notes?: string;
  startedAt?: string; // ISO — when logging began
  completedAt?: string; // ISO — when finished (for duration)
  exercises: LoggedExercise[];
}

export interface BodyWeightEntry {
  date: string; // ISO
  weight: number;
}

/** A point in an exercise's life-cycle sparkline. */
export interface LifePoint {
  date: string;
  e1rm: number;
  rating: 0 | 1;
  repsAtBottom: boolean;
}

export interface ExerciseLifeCycle {
  id: string;
  exerciseName: string;
  pattern: Pattern;
  startDate: string;
  endDate?: string;
  status: LifeStatus;
  startTopSetE1RM: number;
  currentTopSetE1RM: number;
  strengthGained: number;
  durationWeeks: number;
  weakPointTag?: string;
  series: LifePoint[];
}

export interface VariationRosterEntry {
  pattern: Pattern;
  exerciseName: string;
  durationWeeks: number;
  strengthGained: number;
  effectiveness: number; // strengthGained / durationWeeks
  endedAt?: string;
  active: boolean;
}

export interface Settings {
  units: Units;
  language: Language;
  notifications: boolean;
  startWeekday: number;
  restSeconds?: number; // default rest-timer length
  barKg?: number; // barbell weight for the plate calculator (kg)
  barLb?: number; // barbell weight for the plate calculator (lb)
}
